# Generated by Django 4.2.2 on 2023-06-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_courses_courseusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
